
Epoch [1/10]
Traceback (most recent call last):
  File "/notebooks/s2_multiencoder/linear_probing_multi_s2/main.py", line 175, in <module>
    best_ckpt_path = train_dual_encoder_probe(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/notebooks/s2_multiencoder/linear_probing_multi_s2/train.py", line 74, in train_dual_encoder_probe
    outputs = model(clip_imgs, dino_imgs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/notebooks/s2_multiencoder/linear_probing_multi_s2/model.py", line 58, in forward
    clip_out = multiscale_forward(
               ^^^^^^^^^^^^^^^^^^^
TypeError: forward() got an unexpected keyword argument 'forward_fn'